# This name will appear in the "Actions" tab of your GitHub repository.
name: Build and Push Java Docker Image

# This workflow runs automatically on any push to the "master" branch.
on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using your secrets.
      # Make sure you have DOCKER_USERNAME and DOCKER_PASSWORD secrets in your repository settings.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx for advanced build features.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build the image from the Dockerfile and push it to Docker Hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # The build context is '.', the root of the repository, so it can see pom.xml and src/.
          context: .
          # --- FIX: Explicitly point to the Dockerfile inside the 'src' directory ---
          file: ./src/Dockerfile
          push: true
          # The image will be tagged as 'thushanm/online-book-shop:latest'.
          tags: thushanm/online-book-shop:latest
