name: Java CI/CD with Maven and Docker

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker Buildx for multi-platform builds
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.11.0

      - name: Build & push multi-platform Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          # Replace 'your-dockerhub-username/your-repo-name' with your actual image name
          image: your-dockerhub-username/your-repo-name
          registry: docker.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          overrideDriver: true
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
